### ISSUE TITLE
"You attempted to import /.../esm/slicedToArray which falls outside of the project src/..."

### ISSUE THREAD

**Issue by amagee** [ReactUnity/core#24] opened 2021-08-31 11:28 UTC
If I write a component that tries to use the React `useState` hook, I get the following error from the `yarn start` process:

```
Failed to compile.

Module not found: Error: You attempted to import /path/to/react/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/slicedToArray which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.
```

Note: I get the same error from a clean checkout of the `full-sample` repo.

I'm able to work around the problem by hacking out the check in ModuleScopePlugin.js in react-dev-utils:

```
diff --git a/react/node_modules/react-dev-utils/ModuleScopePlugin.js b/react/node_modules/react-dev-utils/ModuleScopePlugin.js
index e84d2b3..0c1cf46 100644
--- a/react/node_modules/react-dev-utils/ModuleScopePlugin.js
+++ b/react/node_modules/react-dev-utils/ModuleScopePlugin.js
@@ -56,6 +56,7 @@ class ModuleScopePlugin {
         // Find path from src to the requested file
         // Error if in a parent directory of all given appSrcs
         if (
+          false &&
           appSrcs.every(appSrc => {
             const requestRelative = path.relative(appSrc, requestFullPath);
             return (
```

but I'm sure there is a more sensible solution.

**Comment by KurtGokhan** [comment] 2021-08-31 11:56
Some questions:

- Which OS?
- Node version?
- Are you importing `@babel/runtime`?

**Comment by amagee** [comment] 2021-09-01 04:56
Hey, thanks for looking into this.

> Which OS?

Ubuntu 21.04

> Node version?

v16.6.2

> Are you importing @babel/runtime?

Not that I know of - I haven't imported it myself. I may be importing something that uses it.

> Did you make any changes to tsconfig.json or did you add a .babelrc?

Nope, just double checked there's no such changes in my `full-sample` checkout.

> Can you post your yarn.lock file

Sure can. [yarn.lock.txt](https://github.com/ReactUnity/core/files/7088334/yarn.lock.txt)

**Comment by KurtGokhan** [comment] 2021-09-01 09:54
Indeed, the issue was reproducible in Ubuntu.

Added a fix to `@reactunity/scripts`. You should upgrade it to version `0.4.1` in your `package.json`.

Some info: `scripts` is based on CRA v4 and this issue was fixed in CRA v5 alpha. `scripts` will be updated to CRA v5 when it is released. The fix I did is a temporary solution.

**Comment by KurtGokhan** [comment] 2021-09-01 15:51
Also, I noticed more issues in `full-sample` and fixed them. `full-sample` is not intended for users to use, but I guess it is the best sample so far and I don't have time to maintain another sample project yet.

Closing this issue. Feel free to reopen if something else is not working.

**Closed by KurtGokhan** 2021-09-01 15:51 UTC
Labels: bug

**Comment by amagee** [comment] 2021-09-02 00:19
Yep the new version fixed the issue for me, thanks!
