### ISSUE TITLE
Inconsistent element rendering

### ISSUE THREAD

**Issue by noah-potter** [ReactUnity/core#88] opened 2023-03-22 02:39 UTC
On my machine, elements are not consistently being rendered. This only happens when the game is started. I've created a bare bones reproduction repo that includes some pics/vids and more detail:

https://github.com/noah-potter/ReactUnityStressTest

My current guess is that it has something to do with rendering a lot of elements at once. I've noticed the missing components are running their logic like normal, it's just that they never make it to the UI.

**Comment by KurtGokhan** [comment] 2023-03-23 12:46
Interesting. I could observe the bug. It only happens in UI Toolkit renderer and not UGUI renderer.

Thank you very much for reporting. I will try to fix this soon.

**Comment by KurtGokhan** [comment] 2023-03-26 16:29
Fixed this in main branch. Will release soon.

It was caused by elements getting collected by GC before they were rendered. So it could happen more frequently on devices with less memory. It didn't happen in UGUI because Unity holds a reference of elements in UGUI so they are not GCed.

**Comment by KurtGokhan** [comment] 2023-03-31 19:47
Fixed in 0.15.2

**Closed by KurtGokhan** 2023-03-31 19:47 UTC
Labels: bug, uitoolkit, pending fix

**Comment by noah-potter** [comment] 2023-04-06 04:48
Just confirming this fixed my issue. Thank you!
