### ISSUE TITLE
Rounded borders rendering is not like in the web standard

### ISSUE THREAD

**Issue by katas94** [ReactUnity/core#42] opened 2022-04-11 08:44 UTC
In the web, rounded border radius is computed differently for the outer and inner edges of the border, so the border can maintain it's width constant through the curve:
* The outer edge has the full given border radius.
* The inner edge has the full given border radius minus the width of the border (clamping negative values to 0).

Currently in ReactUnity, we are using a shader that computes the full given radius for both edges, resulting in extra thickness for the rounded borders at the corner curve.

Here are some comparison screenshots of Web versus ReactUnity
![](https://cdn.discordapp.com/attachments/884829138991603795/962809762687381584/unityreact_boxes.png)

As a bonus, it would be nice to implement some antialiasing to remove the jagged edges.

**Comment by KurtGokhan** [comment] 2022-04-12 19:26
A small progress report on this:

The problem is easy to understand, but hard to solve. It is like the definition of difference between an easy and a difficult border radius implementation.

I fixed it to be good enough. But there will be some cases where it does not render like browsers. These are some edge cases (literally). But at the same time they could be common cases for some people. In any case, these will be ignored until someone discovers and complains about it.

I wanted to implement `border-image` for a while. A complete rewrite of border shaders will be needed for that. I will have to consult to the Chrome source code to implement it perfectly. Probably, all of these issues will be fixed then. But that will be much later. 

I won't push the changes for now. I want to implement all of the [border-radius](https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius) before I push. For example, two values for a single corner did not work before, but they will be working with this change.

**Comment by katas94** [comment] 2022-04-20 18:33
That is great, thanks a lot for the effort. I would love to help with this but I really don't have any time available for now. I'm also not very skilled with shaders.

**Comment by KurtGokhan** [comment] 2022-04-29 18:57
Improved rounded borders in version 0.10.0.

I will close this issue after a few days if there are no more issues.

**Closed** 2022-05-09 14:39 UTC
Labels: enhancement

**Comment by KurtGokhan** [comment] 2022-05-10 22:01
I did some research on how to do anti-aliasing on borders. I found a solution that somewhat worked. But it broke other parts of borders so I didn't enable it. Adding the comparison here for future reference.

<img width="1145" alt="BorderQuality" src="https://user-images.githubusercontent.com/6034931/167728954-f25f4ec2-1ce3-4c01-b814-6fe259ab34de.png">
